#!/bin/bash

max=0

for file in euler*.py; do
    if [[ -f "$file" ]]; then 
        file="${file#euler}"
        file="${file%.py}"
        if (( file > max )); then
            max="$file"
        fi
    fi
done

let max++

mkpython () 
{ 
    touch "$@" && chmod +x "$@" && { 
        echo '#!/usr/bin/env python3' | tee -a "$@" > /dev/null
    }
}

mkpython "euler${max}.py"
vim "euler${max}.py"
